import {StyleSheet} from 'react-native';

export const CreateTaskFormStyle = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    // backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  formContainer: {
    width: '100%',
    maxWidth: 800,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2C7D3F',
    paddingHorizontal: 16,
    height: 48,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  closeButton: {
    padding: 4,
  },
  formContent: {
    // padding: 16,
    maxHeight: 600,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 10,
    backgroundColor: 'white',
  },
  taskTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  taskTypeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    maxWidth: 188,
    maxHeight: 52,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    backgroundColor: 'white',
    marginHorizontal: 4,
  },
  tractorBackground: {backgroundColor: '#E6A23C'},
  waterBackground: {backgroundColor: '#409EFF'},
  selectedTaskType: {
    borderColor: '#2C7D3F',
    borderWidth: 2,
  },
  iconContainer: {
    width: 28,
    height: 28,
    borderRadius: 16,
    backgroundColor: '#409EFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  taskTypeText: {
    fontSize: 13,
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 10,
    backgroundColor: 'white',
    flex: 1,
    marginRight: 8,
  },
  dropdownText: {
    color: '#555',
  },
  calendarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    padding: 10,
    backgroundColor: 'white',
    flex: 1,
    marginLeft: 8,
  },
  calendar: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingBottom: 12,
    paddingHorizontal: 12,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    backgroundColor: '#f9f9f9',
    flex: 1,
    marginRight: 8,
  },
  cancelButtonText: {
    color: '#555',
    marginLeft: 4,
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 4,
    backgroundColor: '#2C7D3F',
    flex: 1,
    marginLeft: 8,
  },
  saveButtonText: {
    color: 'white',
    marginLeft: 4,
  },
});
